### ISSUE TITLE
Image breakpoints disappear after upgrading to Statamic 3.3 and statamic-responsive images 2.10.0

### ISSUE THREAD

**Issue by josephrlee** [spatie/statamic-responsive-images#110]
After upgrading to Statamic 3.3, I'm having issues with the add-on not keeping the breakpoint images saved. After adding an image to take advantage of the art-direction features, I save it, but after I refresh the page, the image disappears. (Here's a recording of the bug/issue.)

Here's the error I see in the log: `local.ERROR: Could not find asset` Any ideas on what's happening here?

https://user-images.githubusercontent.com/1631062/158945049-d631d4ae-0faf-4b7d-bc18-832304bfe74f.mp4

**Comment by riasvdv** [comment]
Should be fixed in 2.10.1!

**Comment by joseph-d** [comment]
Unfortunately, I am still experiencing this issue in 2.10.1 and Statamic 3.3.1.

It also seems as though when two "responsive" fieldtypes are added to the same blueprint (I have them on separate tabs) they are somehow getting merged together as though they were the same field whereas in previous versions it worked fine.

**Comment by joseph-d** [comment]
Ok, the control panel it working fine now and the DEBUG error is no longer appearing in the logs so for the most part it is working now.

However, it seems as though the focal point is no longer being respected when images are rendered. I haven't changed anything else so I suspect it may be something to do with the update but there are no errors appearing anywhere.

**Comment by josephrlee** [comment]
Looks like it's all fixed for me, but I'm not seeing my old breakpoint images anymore in the cp unless I manually re-add and save them.

**Comment by joseph-d** [comment]
I have done some more testing and I have found that with a focal point set in an image, it is **not** respected if "Fit" is set to "Focal Crop" as it was before the recent updates.

However, the focal point **is** respected if the "Fit" is set to blank / null value.

**Comment by josephrlee** [comment]
> 

Yes, I saw that the structured data changed after the update as well.
