### ISSUE TITLE
Responsive Image tag used in Replicator or Bard: JS error

### ISSUE THREAD

**Issue by goellner** [spatie/statamic-responsive-images#51]
when adding a new set to a replicator, which contains a responsive image tag, it throws a js error, when opening the asset browser. saving the entry and reloading the page fixes this. seems like the javascript does not get initialised properly when the field gets dynamically added.

**Comment by stoffelio** [comment]
I have the same issue using responsive fields within a grid. This is the error message:

> vue.common.prod.js:6 TypeError: Cannot read property 'length' of undefined
>     at a.<anonymous> (Selector.vue?f4b4:1)
>     at a.e._render (vue.common.prod.js:6)
>     at a.r (vue.common.prod.js:6)
>     at fn.get (vue.common.prod.js:6)
>     at new fn (vue.common.prod.js:6)
>     at vue.common.prod.js:6
>     at a.wn.$mount (vue.common.prod.js:6)
>     at a.wn.$mount (vue.common.prod.js:6)
>     at init (vue.common.prod.js:6)
>     at vue.common.prod.js:6

**Comment by goellner** [comment]
Just a guess, but maybe you need to wrap your JS in the statamic booting method, like I did here: https://github.com/goellner/statamic-3-table-on-steroids/blob/main/resources/js/index.js

**Comment by riasvdv** [comment]
v2.5.0 released which should solve this

**Comment by goellner** [comment]
unfortunately that didn't help and it is still throwing a js error when used in a replicator

**Comment by riasvdv** [comment]
I'm pretty stuck on this, can't seem to figure out if it's something I'm doing wrong or if it might be a bug inside the replicator/bard components. Could use some help on this

**Comment by riasvdv** [comment]
Should be fixed in 2.5.3!

**Comment by goellner** [comment]
Just had the time to update this on a current project and the JS error is gone, but it does not save the selected image. The asset selector opens fine now and lets you select an image, but the value does not get saved.

Steps to reproduce: 

Add a **new** replicator item with a responsive image field in it.
Select an image
Save the entry
Open the .md file of the entry (image does not get saved)
Reload the entry edit page in the cp
Select an image 
Save
Open .md and field is saved correctly

When you have two field in the replicator (e.g. text field and responsive images field) and do the following the value gets deleted right away without saving:

Add new replicator block (which has a normal text field an a responsive image field set up)
Select an image
Write something in the text field 
The image preview and value in the vue component gets deleted right away

**Comment by codedge** [comment]
I can confirm the behaviour described by @goellner with having multiple fields (responsive image, additional text fields) in the replicator. For me it is a little different:

1. Selecting the image
2. Editing another text field
3. CTRL+S -> only the text field is saved, not the image.

The image does not directly disappear when entering text, but leads to the same result.

**Comment by adnakurtic** [comment]
The same issue here as @goellner mentioned! Image is not saved the first time. Need to do everything twice!

**Comment by codedge** [comment]
With the current Statamic version `3.1.5` I _do not_ run into this issue anymore. Saving works immediately. Values entered in fields additional to the image fields also persist with the first save.

**Comment by riasvdv** [comment]
@adnakurtic Can you confirm this is also fixed for you? Might have been a Statamic issue then
